services:
  todobackend:
    build:
      context: .
      dockerfile: TodoBackend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User=sa;Password=YourStrongP@ssw0rd;TrustServerCertificate=True;
    networks:
      - todoapp-network
    depends_on:
      - db

  todo-frontend:
      image: node:18
      ports:
        - "5173:5173"
      volumes:
        - ./todo-frontend:/app
        - /app/node_modules
      working_dir: /app
      command: >
        sh -c "npm install && npm run dev -- --host"
      networks:
        - todoapp-network
      depends_on:
        - todobackend

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongP@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - todoapp-network

networks:
  todoapp-network:
    driver: bridge

volumes:
  sqlserver_data:
